'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { join } = require('node:path');
const root = join(__dirname,'..');
const html=fs.readFileSync(join(root,'dashboard.html'),'utf8');
const js=fs.readFileSync(join(root,'assets/js/dashboard/world-manager.js'),'utf8');
const lazy=fs.readFileSync(join(root,'assets/js/dashboard/lazy-assets.js'),'utf8');
const css=fs.readFileSync(join(root,'assets/css/dashboard/world-manager.css'),'utf8');
const sw=fs.readFileSync(join(root,'sw.js'),'utf8');
for (const token of ['data-nav-label="World Manager"','data-dashboard-section="world-manager"','data-world-profiles','data-world-checks','data-world-role-preview','data-world-cache-warning','data-world-refresh']) assert(html.includes(token),`Missing UI ${token}`);
assert(html.includes('data-staff-only="" hidden="" id="dashboard-admin-world-manager"'),'World Manager protected by staff UI gate');
assert(js.includes('DASHBOARD_API_BASE}/api/admin/world-profiles'),'World Manager API from canonical base');
assert(js.includes('authFetch('),'Authenticated request required');
assert(js.includes("payload.status !== 'ok'"),'Response checks');
assert(js.includes('role.member_cache_complete'),'Cache completeness surfaced');
assert(!js.includes("method:'POST'") && !js.includes('add_roles') && !js.includes('remove_roles'),'Read-only panel');
assert(lazy.includes('ensureWorldManager') && lazy.includes("section === 'world-manager'"),'Lazy asset routing');
assert(css.includes('world-check[data-state="ready"]'),'Readiness styling');
assert(sw.includes("WWZ_PWA_VERSION = '2.5.0'"),'PWA version updated');
console.log('World Manager v2.5.0: 16 readiness, safe-panel and lazy-routing checks passed');
